### ISSUE TITLE
制作用户注册的相关接口

### ISSUE THREAD

**Issue by mitoriko** [A-Cubic/CBEC-B2B#5]
采购商、供货商注册的接口支持
1、部分后台验证
2、注册成功失败

**Comment by legendaryfly** [comment]
补充接口地址说明
1.获取验证码：/llback/user/register/code
请求参数：{"mail":"邮箱地址"}
返回参数：邮件已发送 或 42s（离下次发送验证码的剩余时间）

2. 提交注册：/llback/user/register/submit
请求参数：{"mail":"邮箱地址","captcha":"验证码","password":"密码","type":"用户类型"}
返回参数：注册成功/失败
